CREATE TABLE `jobs` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `datetime_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `datetime_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `command` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  UNIQUE KEY `idcommand_UNIQUE` (`id`, `command`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8