CREATE TABLE `statuses` (
  `id` int(1) UNSIGNED NOT NULL AUTO_INCREMENT,
  `datetime_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `datetime_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `name` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  UNIQUE KEY `idname_UNIQUE` (`id`, `name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8